# Generated by Django 5.1.6 on 2025-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
