# Generated by Django 5.1.6 on 2025-03-03 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_share_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.share'),
        ),
        migrations.AddField(
            model_name='share',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='share_liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
