# Generated by Django 5.1.6 on 2025-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_updated_at_post_updated_at_share_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='share',
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
