# Generated by Django 5.1.6 on 2025-03-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_share_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.share'),
        ),
    ]
