# Generated by Django 5.1.6 on 2025-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='share_images/'),
        ),
    ]
